//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synrc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Synrc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synrc Contacts.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap clear {
            get {
                object obj = ResourceManager.GetObject("clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- Copyright Microsoft Corporation. All Rights Reserved. --&gt;
        ///
        ///&lt;xs:schema
        ///           xmlns:xs=       &quot;http://www.w3.org/2001/XMLSchema&quot;
        ///           xmlns:ext=      &quot;http://schemas.microsoft.com/Contact/Extended&quot;
        ///
        ///           xmlns:tns=      &quot;http://schemas.microsoft.com/Contact&quot;
        ///           targetNamespace=&quot;http://schemas.microsoft.com/Contact&quot;
        ///
        ///           elementFormDefault=    &quot;qualified&quot;
        ///           attributeFormDefault=  &quot;qualified&quot;
        ///           version=&quot;1.0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;c:contact c:Version=&quot;1&quot;
        ///    xmlns:c=&quot;http://schemas.microsoft.com/Contact&quot;
        ///    xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;c:Extended xsi:nil=&quot;true&quot;/&gt;
        ///  &lt;c:CreationDate&gt;2000-01-01T00:00:00Z&lt;/c:CreationDate&gt;
        ///  &lt;c:ContactIDCollection&gt;
        ///    &lt;c:ContactID c:ElementID=&quot;00000000-0000-0000-0000-000000000000&quot;&gt;
        ///      &lt;c:Value&gt;00000000-0000-0000-0000-000000000000&lt;/c:Value&gt;
        ///    &lt;/c:ContactID&gt;
        ///  &lt;/c:ContactIDCollection&gt;
        ///&lt;/c:contact&gt;
        ///
        ///.
        /// </summary>
        public static string emptycontact {
            get {
                return ResourceManager.GetString("emptycontact", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
